### Obtener todos los hashtags
GET http://localhost:9999/hashtag

### Obtener hashtag por ID
GET http://localhost:9999/hashtag/1

### Crear un nuevo hashtag
POST http://localhost:9999/hashtag
Content-Type: application/json

{
  "etiqueta": "nuevo1"
}

### Actualizar un hashtag
PUT http://localhost:9999/hashtag/1
Content-Type: application/json

{
  "etiqueta": "nuevo2"
}

### Eliminar un hashtag
DELETE http://localhost:9999/hashtag/1